services:
  postgres:
    image: postgres:15-alpine
    container_name: ms-compras
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: icomprasprodutos, icompraspedidos, icomprasclientes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/docker/postgres/data:/var/lib/postgresql/data
